### ISSUE TITLE
Offer quantity doesn't update when buyer uses escrow

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin#101]
Purchase quantity should be deducted from offer quantity when buyer moves a transaction into escrow. It does not.

**Comment by sidhujag** [comment]
please retest in testnet 2b... also note that if people are reselling that offer that it they should all also deduct their qty since offers and their reseller offers should all match qty at all times.

if you purchase a linked offer, it should update the root offer and any other reseller offers of that root offer aswell

**Comment by sidhujag** [comment]
please retest
