### ISSUE TITLE
3.0.6.0 Lock unspent

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#230]
I locked an input to ensure I could not spend it. Closed 3.0.6.0 and reopened it and the input was no longer locked. This is not a MN wallet

**Comment by sidhujag** [comment]
can you call listlockunspent in the cli to see if it shows up there

**Comment by johnp1954** [comment]
No it doesnt

**Comment by sidhujag** [comment]
@willyko can you take a look

**Comment by willyko** [comment]
this is the expected behaviour.  quoting syscoin-cli lockunspent help message 
`Temporarily lock (unlock=false) or unlock (unlock=true) specified transaction outputs.
If no transaction outputs are specified when unlocking then all current locked transaction outputs are unlocked.
A locked transaction output will not be chosen by automatic coin selection, when spending syscoins.
Locks are stored in memory only. Nodes start with zero locked outputs, and the locked output list
is always cleared (by virtue of process exit) when a node stops or fails.`
