### ISSUE TITLE
You people ****** me.

### ISSUE THREAD

**Issue by ghost** [syscoin/syscoin#244]
Piece of shit wallet backup.

/goldclap

inept developers .

**Comment by evscott** [comment]
Describe your issue?

**Comment by ghost** [comment]
Im angry and my words are not making sense atm.

Still trying my best ...

I apologise for harsh words...

Need to go over everything first ... but my wallet.dat is corrupt?

Again .. looking over everything as I totally lost my mind at this very moment.

**Comment by ghost** [comment]
The "backup" from Blockmarket are so silly I have no words .. I remember I did it and asked myself wtf.

It gave me a wallet.dat and now it's useless .. old blockmarket doesn't open anymore? it's like it never existed.

And why does the strange blockmarket backup turn it into a DUMB file? when it gave me a .dat file.

How is that possible?¨

" http://localhost:8001/dumpprivkey?address= my alias "

Why is this so complicated when every other wallets out there works smooth.

I can't even install the new wallet .. the old wallet refuses to go past the SYSCOIN loading screen.

**Comment by ghost** [comment]
Older wallets are also telling me my .dat is corrupted.

Any DEV that wants it?

Can I just throw it to my trash bin now?

Cause nothing works, nothing.

Lost all coins and I have totally lost the taste of syscoin.

**Comment by ghost** [comment]
C:\Users\Public\sys2dump.bmwalletdump

What is this?

It must be fun making it so insanely unnecessary.

so wallet.dat is useless regardless cause it's not what it wants...

************* !

**Comment by ghost** [comment]
yeah ... expected ... nothing .

Good luck with your strange "backup" system .

Im out .. link me a mail I can give away my .dat 

/facepalm

**Comment by jnessbcf** [comment]
Hi Illustratum!  Nice name.  Good passion.  I like your fire.  And I appreciate your frustration.  It's annoying to have to figure this process out and moving from "chain to chain", so to speak, is a bit more complicated than we'd like.

We're also not really on 24/7 level support here so apologies for any delay in terms of wallet.dat/dump/etc frustrations.  Judging from your messages you look like your expectation is a response time < 5 min.  Not sure how possible that is, just to set expectations. 

Now for questions:

Are you trying to backup your wallet from either 
Blockmarket Desktop 1.2
Syscoin 2.x

to import it into 3.x?


Your support issue reads like you're trying to backup a wallet from BMD 3.0 (which uses Syscoin 3.x, which is a different version - that dump wouldn't help port over your stuff from an older version of Syscoin).  

Let us know and hopefully we can help you out!

Otherwise I'm happy to provide you an E-mail with which to send your wallet.dat ;) but hopefully we can avoid that and make you a happy camper again!

Peace,
J

**Comment by ghost** [comment]
Syscoin 2.1.6.0-3babe9d accepted my .dat

But no connections ... cause Im late?

***

Will adding nodes help in .conf ?

**Comment by ghost** [comment]
I hate my tunnel vision atm ... 😠 I should stay away and cool off.

Im sorry.

**Comment by jnessbcf** [comment]
Okay, this explains your issue - you need to:
a) get your wallet exported (I know the terminology is confusing a bit here) *from* Sys 2.1.6
b) import your wallet into Sys 3.x

This link should help you out some:

https://medium.com/@bittyjohn1954/syscoin-3-conversion-from-syscoin-2-579a8cf02603

Keep us posted or join the syscoin slack and we can continue diagnosis there!  And no worries, heatedness happens. =)  The important thing is getting you back up and running!

**Comment by ghost** [comment]
Thank you for your patience 🙈

**Comment by ghost** [comment]
Im creating a new backup with nothing on :(

I need to convert .dat to this? 

again.. tunnel vision.

Wallet.dat inside folder with 1.2.3 .... do the thing with the " /dumpwallet and press ‘Get’ "

Get that file imported to the new wallet when it's synced.

🤔

**Comment by jnessbcf** [comment]
Use syscoin 2.x / the old blockmarket with your previous wallet and export as per the instructions above!!  

That'll prep you for putting stuff into either Syscoin 3.x (through the QT console) or through Blockmarket Desktop 3.0 (the more UI-heavy wallet).

**Comment by ghost** [comment]
3am atm and Im so confused by all of this .

corrupt over and over and got Error 500 : Contact team.

**Comment by ghost** [comment]
I gave up, same ERROR no matter what ... contact team ERROR 500 

Contact team ERROR 500 

Why is SYSCOIN the only crypto I have encountered with such painfully process?

Mind boggling ...

**Comment by locutus75** [comment]
Are you in Slack? Please join, we can sort this out. Make sure you have a valid backup of your 2.1.6 QT wallet.dat at all times. 
https://join.syscoin.org/

**Comment by ghost** [comment]
Hello, no Im not.

Sent mail now.

Thanks.


🙈 Im sorry .. I my act is not good.
