### ISSUE TITLE
Restarting Node Leads To NEW_START_REQUIRED

### ISSUE THREAD

**Issue by gaia** [syscoin/syscoin#251]
Ubuntu 16.04, kernel 4.4.0-130-generic
Syscoind 3.0.6.1 (running via systemd)
Sentinel 1.1.1
Sentinel tests:

```
================================= test session starts 
platform linux2 -- Python 2.7.12, pytest-3.0.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/user/daemons/syscoin/bin/sentinel, inifile:
collected 24 items

test/integration/test_jsonrpc.py .
test/unit/test_misc.py .
test/unit/test_models.py ..
test/unit/test_submit_command.py .
test/unit/test_syscoin_config.py .
test/unit/test_syscoind_data_shims.py ...
test/unit/test_syscoiny_things.py ......
test/unit/models/test_proposals.py ....
test/unit/models/test_superblocks.py .....
============================== 24 passed in 0.59 seconds 
```

Conf (in /mnt/syscoin)

```
rpcuser=syscoinrpc
rpcpassword=<pword>
rpcallowip=127.0.0.1
#
listen=1
server=1
daemon=1
maxconnections=24
#
masternode=1
masternodeprivkey=xxxxxxxxxxxxxxxxxxxxxxxxxx
externalip=<public_ip>
bind=<public_ip>
port=8369
```

Service file

```
[Unit]
Description=Syscoin daemon service
After=network.target

[Service]
Type=forking
User=<user>
WorkingDirectory=/mnt/syscoin
ExecStartPre=/bin/sleep 15
ExecStart=/home/user/daemons/syscoin/bin/syscoind -daemon -datadir=/mnt/syscoin
PIDFile=/mnt/syscoin/syscoind.pid
Restart=always
RestartSec=1
KillSignal=SIGQUIT
KillMode=mixed

[Install]
WantedBy=multi-user.target

```

ISSUE: Node needs to be restarted sometimes to backup the chain or install updates on the machine. Issuing `sudo systemctl stop syscoind` followed by `sudo systemctl start syscoind` puts node in NEW_START_REQUIRED. Same for rebooting (service is enabled)

NOTE: Shutting down the service generates a ` systemd[1]: syscoind.service: Failed with result 'core-dump'.`, but so does restarting any other node (for other chains) on this machine and they all work fine after a restart.

I can provide the debug log upon request.

**Comment by willyko** [comment]
How long between shutting down and starting the service?

**Comment by gaia** [comment]
Always less than 5 minutes, sometimes less than 3. I sent locutus on Slack the debug log.

**Comment by doublesharp** [comment]
Where you do you see `NEW_START_REQUIRED`? What is the output of `mnsync status` or `masternode status`? Is it syncing to the tip of the chain?

**Comment by gaia** [comment]
i get it in `mnsync status` and in QT... it is syncing and the status changes to that after it is fully synced.

I think this might be related to `Restart=always` in the service file. I've changed it to

```
Restart=on-success
RestartSec=30
```

and will report back.

**Comment by johnp1954** [comment]
This has now happened to me, i restarted my servers via the VPS console and almost ALL of them have gone to NSR :-( The server reboot was almost instant. The VPS is fully synced to the latest block.
![image](https://user-images.githubusercontent.com/16462796/43165422-cde16c66-8f8b-11e8-93fd-ff13198f6e90.png)

**Comment by johnp1954** [comment]
I have done this before without any issues

**Comment by johnp1954** [comment]
In the Logs there is this 
2018-07-24 20:14:30 CMasternodePing::CheckAndUpdate -- Masternode ping is invalid, block hash is too old: masternode=fd6330604b5eb03837ee377e387bf49753fae38667dfc6773a9f7f907e598bef-0  blockHash=5ff32eca96208325faba2c7a0a0232cc49025c48ff452707cf9d481b68d94767

Is this because of the mempool issues
And in another one
2018-07-24 20:03:10 CMasternodePing::CheckAndUpdate -- Masternode ping is invalid, block hash is too old: masternode=145a4f3ffa81f03243073e46b4c48bf1f4f5842bce79f40c593685ba1b7e5b52-1  blockHash=e83ec4916bcdfac17eb80cd94678382fb22ab3b5435b47aee7e199d9eaf8d8b1
2018-07-24 20:03:10 CActiveMasternode::ManageStateRemote -- NOT_CAPABLE: Masternode in NEW_START_REQUIRED state
2018-07-24 20:03:10 CMasternodeBroadcast::Update -- Got UPDATED Masternode entry: addr=45.55.136.240:8369
