### ISSUE TITLE
on rescans, getting wrong time for new found txs

### ISSUE THREAD

**Issue by c-e-d-git** [syscoin/syscoin#268]
When the wallet scans for missing txs, new found txs are set to the actual time in the wallet transaction list instead of the time of the block they are included in.
Even with the variances in timestamps of blocks it would be better than actual time of search.
Something like  min (blocktime, actual time)  to prevent timestamps into the future.

**Comment by Keyare** [comment]
Is this issue related to syscoin core or BMD?


Sent from Mail for Windows 10

From: cydg
Sent: August 27, 2018 6:12 AM
To: syscoin/syscoin
Cc: Subscribed
Subject: [syscoin/syscoin] on rescans, getting wrong time for new found txs(#268)

When the wallet scans for missing txs, new found txs are set to the actual time in the wallet transaction list instead of the time of the block they are included in.
Even with the variances in timestamps of blocks it would be better than actual time of search.
Something like min (blocktime, actual time) to prevent timestamps into the future.

**Comment by c-e-d-git** [comment]
Sorry, it's core code. 99% sure inherited from btc code.
Not especially tested in BMD

**Comment by c-e-d-git** [comment]
Now tested in BMD 3.1.3:
It takes the time of the last know tx before the scan/reindex for every missing tx found.
Even more confusing than actual time of the scan.
Like said above, blocktime of tx is far better.

**Comment by Keyare** [comment]
Yes this is a known issue and we have a task assigned to fix it - or at
least work around the BTC code for 3.2. We came to the same conclusion:
showing the block height would be more useful than what we show presently.

**Comment by c-e-d-git** [comment]
Shouldn't be a big deal to grab the time when scanning the blocks for transactions.
i.e.
getblockhash 185000
a38ce7a0ff353b0377f0d07ddd8f91be3c6bf62c020b0e4f56ba8f313897b265

getblock a38ce7a0ff353b0377f0d07ddd8f91be3c6bf62c020b0e4f56ba8f313897b265
{
  "hash": "a38ce7a0ff353b0377f0d07ddd8f91be3c6bf62c020b0e4f56ba8f313897b265",
  "confirmations": 2791,
  "size": 2931,
  "height": 185000,
...
  "**time**": 1536784391,
  "**mediantime**": 1536784139,
  "nonce": 0,
  "bits": "1808ab60",
  "difficulty": 126824300419.4244,
...
}
time or mediantime, not a big difference and close enough

**Comment by Keyare** [comment]
Closed. Deprecated version.
