### ISSUE TITLE
Chain Stuck on Testnet 4.1.0

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#367]
On Testnet only. Sent an SPT followed by a SYS transaction in the same block, the chain halted. Input already used.

**Comment by willyko** [comment]
`2019-07-19T20:38:05Z ERROR: ConnectBlock: Consensus::CheckTxInputs: 623eb6bd43f8b55268e71603463e3d60e3d5d74e0199f154a9aecfb0a4adf344, bad-txns-inputs-missingo
rspent, CheckTxInputs: inputs missing/spent (code 16)`

Looks like it has to do with miner code with the new output linking change.  Testing a fix right now

**Comment by sidhujag** [comment]
Upon further investigation looks like the the ordering graph by time caused output linking to place the dependent transaction BEFORE the dependent transaction because the dependent transaction was a standard syscoin transaction that doesn't get ordered by time. This was resolved in my new branch im working on related to enforcement of CPFP on asset transactions and thus I could remove ordering by time which is a distributed systems faux pax anyway, removed in commit: https://github.com/syscoin/syscoin/commit/39ce2cac8d001031582cd9ae4533336e772d7e3d

The miners have been updated and be able to mine, but to be clear although miners could not miner the chain was not forked.
