### ISSUE TITLE
dev-4.x   syscoind processes spawn infinitely - geth & relayer do not spawn at all

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#413]
**Expected behavior**
A single instance of syscoind, sysrelayer.nod and sysgeth.nod

**Actual behavior**
New syscoind processes are spawned without end, while sysrelayer and sysgeth are never spawned

**To reproduce**
Start syscoind from any directory other than `~/syscoin/depends/x86_64-pc-linux-gnu/bin`.  If you start it from that directory everything works correctly.

Please note that my PATH environment variable value is correct, as follows:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/syscoin/depends/x86_64-pc-linux-gnu/bin:~/syscoin/depends/x86_64-pc-linux-gnu/bin`

also, I did perform `make install` after all compiling was complete.

**System information**

Syscoin 4.2 - dev-4.x - commit hash 51e7408d7a05716fc28f46819b352581cd50b428 (also applies to previous 4.2 commit hashes I've tried)

Ubuntu 20.04  (**note:  this issue also occurs on 18.04**)

**Comment by sidhujag** [comment]
Can you try dev4x?

**Comment by sidhujag** [comment]
this should be fixed the way we handle geth relayer which will download a descriptor and then fetch and compare a checksum, it will put the binary in the syscoin data folder and run it from there. To try it you either need to be a masternode or set the "-gethsyncmode" start up command line argument. You can set it to "light" to match your expected settings. Other settings are "fast", "full" or "disabled".

fast = geth fast sync mode, its full but syncs headers first, full = full mode including all states, disabled = you are running geth somewhere else and redirect localhost queries for geth to a remote node (f2pool does this) so that the relayer can query through rpc and websockets on eth blocks/headers.
