### ISSUE TITLE
Why syscoin is rolling back the chain?

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#541]
I had an issue with syscoin masternode, it stucks, so I copied whole data folder (except config) from working node, and after start syscoin starts to roll back the chain, why, it that related to the sentinel.db state? I tried to delete sentinel.db to have "fresh" start and the node still rollbacks freshly copied data.

And what does it trying to do?

![sys](https://github.com/syscoin/syscoin/assets/2981715/a13d2de0-0a32-4b45-9eec-53813f85d30d)

**Comment by skironDotNet** [comment]
2024-03-11T16:50:07Z init message: Verifying blocks…
2024-03-11T16:50:07Z Verifying last 6 blocks at level 3
2024-03-11T16:50:07Z Verification progress: 0%
2024-03-11T16:50:08Z Verification progress: 16%
2024-03-11T16:50:08Z Verification progress: 33%
2024-03-11T16:50:08Z Verification progress: 50%
2024-03-11T16:50:08Z Verification progress: 66%
2024-03-11T16:50:08Z Verification progress: 83%
2024-03-11T16:50:08Z Verification progress: 99%
2024-03-11T16:50:08Z Verification: No coin database inconsistencies in last 6 blocks (14 transactions)
2024-03-11T16:50:08Z  block index           21523ms
2024-03-11T16:50:08Z init message: Loading Geth...
2024-03-11T16:50:13Z Geth nHeightFromGeth 363258 nHeightLocalGeth 469844
**2024-03-11T16:50:13Z Geth nHeightFromGeth 363258 vs nHeightLocalGeth 469844, rolling back...**
2024-03-11T16:50:13Z Leaving InitialBlockDownload (latching to false)

**Where does the Geth keeps nHeightFromGeth? is it in sentinel.db?**

**Comment by Frank-GER** [comment]
Nothing to do with sentinel.

This rollback happens if the saved states of utxo and nevm are out of sync; usually a result of of a failed/unclean shutdown.
"Geth nHeightFromGeth 363258 vs nHeightLocalGeth 469844"
The height returned from geth doesn't fit to the height expected from utxo.
Always do a _syscoin-cli stop_ and wait for it to finish before shutting down the node.

**Comment by skironDotNet** [comment]
Can you tell where Geth keeps it's info? I would like to snap shot it once a while, after I bring the node to correct state.

Also my node failed a month ago which is no way to be 469844 height provided "current" is 
height=1723968 version=0x20100180 log2_work=92.100879 tx=2927519 date='2023-11-21...'

it feels like it's going back to rollback to "zero"

**Comment by skironDotNet** [comment]
I think I know, it's a geth folder? and I copied chain from non master node that is not using Geth thus I'm at "zero" point. I think I have more recent backup of the masternode state.
Can you just please confirm it's a geth folder under syscoin's data folder?
Thanks!

**Comment by Frank-GER** [comment]
NEVM started at UTXO block 1317500; so that is the difference between height shown for UTXO blocks in debug.log and NEVM blocks shown in sysgeth.log.

Since NEVM blocks are anchored in corresponding UTOX blocks, I wouldn't try to copy them from different nodes.
You would still have to reindex; to simply copy the geth subdir into the data dir isn't enough.

Take a synced node (with NEVM enabled), shut it down with _syscoin-cli stop_ (check shutdown msgs in debug.log) and than copy the whole data directory. (Change the syscoin.conf on the new new node where necessary)
A node start after a proper shutdown should show the same values for nHeightFromGeth and nHeightLocalGeth in debug.log.

**Comment by skironDotNet** [comment]
Thank you for the info, I also tried the `geth` folder and it did work, but overall it's better to copy the whole data directory to avoid errors. 
Also I do confirm shutdown is important  
> This rollback happens if the saved states of utxo and nevm are out of sync; usually a result of of a failed/unclean shutdown.

YES!

> Always do a syscoin-cli stop and wait for it to finish before shutting down the node.

I docerized my syscoin, so for me it's `docker compose stop -t 120` to let docker know to wait longer for the container to stop.

I hope I will find this next time, and closing for now. @Frank-GER many thanks!
